[package]
name = "utf_symbols"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
crossterm = "0.29.0"
ratatui = "0.29.0"
rayon = "1.10.0"
thiserror = "2.0.12"
tui-prompts = "0.5.0"
tui-textarea = "0.7.0"
unicode_names2 = "1.3.0"
